### ISSUE TITLE
crashes in Crypto

### ISSUE THREAD

**Issue by danipralea** [vapor/open-crypto#100]
Hello guys.
I have this issue when either logging in, or doing any other request. I'm really sorry for not having any more info. I generated the log as well with ```
command script import lldb.macosx.crashlog
save_crashlog /tmp/crash.log
cont``` but the crash.log comes empty. can't even attach it because of that
<img width="1653" alt="Screenshot 2019-10-02 15 04 16" src="https://user-images.githubusercontent.com/768893/66043485-f21d4300-e527-11e9-81eb-fc9301f398a8.png">

### Steps to reproduce

No consistent steps

### Expected behavior

Doesn't crash

### Actual behavior

It crashes in Crypto library

### Environment

* Vapor Framework version: Can't find out. I get `Error: GeneralError(message: "Unable to locate vapor dependency")`
* Vapor Toolbox version: 3.1.10
* OS version: Mac OS 10.14.6

**Comment by adiwajshing** [comment]
I have the same issue on `Vapor 4.17.0`, I get the crash only when I run it with `swift run`. It doesn't crash when running in Xcode for some reason :/

I can reproduce the issue with `Bcrypt` in my vapor app using:
``` swift
eventLoopGroup
.next()
.scheduleTask(in: .seconds(5)) {
    let hash = try Bcrypt.hash("password") // crashes here
    print (hash)
}
```
I just get the following message: `zsh: segmentation fault  swift run`

However, the issue does not occur when I replace `try Bcrypt.hash("password")` with `try Bcrypt.hash("password", salt: "lolz")`. I'm guessing the issue lies in the `generateSalt()` method of Bcrypt

**Comment by tanner0101** [comment]
@adiwajshing that's a separate issue, see https://github.com/vapor/vapor/issues/2265

**Comment by adiwajshing** [comment]
Ah okay, thanks.

**Comment by 0xTim** [comment]
Closing as Swift Crypto is now used instead of this library
