### ISSUE TITLE
Should we archive this repo when we migrate to Swift Crypto?

### ISSUE THREAD

**Issue by 0xTim** [vapor/open-crypto#99]
Since the plan is to migrate Vapor's Crypto reliance to Swift Crypto should this repo be archived to mark the fact that it is no longer maintained. We could potentially lose a couple of helpful wrappers that are common crypto operations and not currently supported by Swift Crypto - namely RSA key support and PEM/DER key support. Anyone wanting these features may need to vend their own copy of BoringSSL whereas we could write a library to support it, until such a time as Swift Crypto adds supports (see apple/swift-crypto#26 and apple/swift-crypto#27)

**Comment by calebkleveter** [comment]
I vote that we create a library similar to AsyncKit that fills those holes.

**Comment by 0xTim** [comment]
I agree, I think a Crypto library built on top of crypto (and our own BoringSSL vended library) is a good thing to provide for users of Vapor until Crypto can plug the gaps. I'm not sure what else other than the above we would want to add but we definitely need to make sure we are careful about what APIs we expose (see discussion [here](https://forums.swift.org/t/discussion-swift-crypto/33964/9?u=0xtim)). Doing this would allow JWT, APNS and anything else that needs it to be built on top of the same library without each having to build their own BoringSSL.

**Comment by tanner0101** [comment]
Yes, I think we should archive this repo since it was meant as a drop in replacement for CryptoKit which is no longer needed. 

Regarding where to put crypto functionality we need, I think Vapor is a fine place for what we already have (like Bcrypt and TOTP). The goal is to have new crypto stuff go into SwiftCrypto directly so I think we should put our efforts toward pitching new functionality there and not creating separate repos.

**Comment by 0xTim** [comment]
Closing as we've migrated to Swift Crypto. Will archive this
